# Copyright (C) 2023 Maxwell G <maxwell@gtmx.me>
# SPDX-License-Identifier: GPL-3.0-or-later
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or
# https://www.gnu.org/licenses/gpl-3.0.txt)

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: "v5.0.2"
    hooks:
      - id: reuse
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "25.1.0"
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: "6.0.1"
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.2"
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies:
          - "antsibull >= 0.60.0"
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.32.1"
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
ci:
  autofix_prs: false
